version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - redis
      - sidekiq
    stdin_open: true
    tty: true

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq -r ./app.rb -C ./config/sidekiq.yml
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL_TEST}
      RACK_ENV: test
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    name: myapp_network
