:concurrency: 10
:queues:
  - default
  - ping_service
  - ping_executor

:scheduler:
  :schedule:
    perform_checks:
      cron: "*/1 * * * *"  # Every 1 minute
      class: PingService
      queue: ping_service
